### ISSUE TITLE
getInstallReferrer does not work

### ISSUE THREAD

**Issue by heroic** [react-native-device-info/react-native-device-info#1243]
## Summary

getInstallReferrer stopped working in our quite sometime ago.

|             |     |
| ----------- | --- |
| Version     | 8.1.3  |
| Affected OS | android   |
| OS Version  | all  |
Installereferrer library version 2.2

## Current behavior

Logcat shows this error(I added a printstacktrace to see what the full error was):

```
2021-05-24 23:43:48.752 21112-21188/? W/System.err: RNInstallReferrerClient exception. getInstallReferrer will be unavailable: com.android.installreferrer.a.a.newBuilder [class android.content.Context]
2021-05-24 23:43:48.752 21112-21188/? W/System.err: java.lang.NoSuchMethodException: com.android.installreferrer.a.a.newBuilder [class android.content.Context]
2021-05-24 23:43:48.756 21112-21188/? W/System.err:     at java.lang.Class.getMethod(Class.java:2072)
2021-05-24 23:43:48.756 21112-21188/? W/System.err:     at java.lang.Class.getMethod(Class.java:1693)
2021-05-24 23:43:48.756 21112-21188/? W/System.err:     at com.learnium.RNDeviceInfo.c.<init>(RNInstallReferrerClient.java:4)
2021-05-24 23:43:48.756 21112-21188/? W/System.err:     at com.learnium.RNDeviceInfo.RNDeviceModule.<init>(RNDeviceModule.java:7)
2021-05-24 23:43:48.756 21112-21188/? W/System.err:     at com.learnium.RNDeviceInfo.b.createNativeModules(RNDeviceInfo.java:2)
2021-05-24 23:43:48.756 21112-21188/? W/System.err:     at com.facebook.react.s.a(ReactPackageHelper.java:7)
2021-05-24 23:43:48.756 21112-21188/? W/System.err:     at com.facebook.react.f.b(NativeModuleRegistryBuilder.java:8)
2021-05-24 23:43:48.756 21112-21188/? W/System.err:     at com.facebook.react.m.P(ReactInstanceManager.java:6)
2021-05-24 23:43:48.756 21112-21188/? W/System.err:     at com.facebook.react.m.Q(ReactInstanceManager.java:8)
2021-05-24 23:43:48.756 21112-21188/? W/System.err:     at com.facebook.react.m.q(ReactInstanceManager.java:6)
2021-05-24 23:43:48.757 21112-21188/? W/System.err:     at com.facebook.react.m.c(ReactInstanceManager.java:1)
2021-05-24 23:43:48.757 21112-21188/? W/System.err:     at com.facebook.react.m$e.run(ReactInstanceManager.java:12)
2021-05-24 23:43:48.757 21112-21188/? W/System.err:     at java.lang.Thread.run(Thread.java:919)
```

## Expected behavior

It should show the referrer. I tested the google implementation with the code sample, and it works. So it seems something about the reflection is a problem, probably, especially because of `com.android.installreferrer.a.a.newBuilder`. The path seems to be different from the actual class.

**Comment by heroic** [comment]
Sample code that is working if I run it in MainApplication.java

```
InstallReferrerClient referrerClient;

      referrerClient = InstallReferrerClient.newBuilder(this).build();
      Log.w("referrer worked", "here");
      referrerClient.startConnection(new InstallReferrerStateListener() {
          @Override
          public void onInstallReferrerSetupFinished(int responseCode) {
              Log.w("referrer worked", "" + responseCode);
              switch (responseCode) {
                  case InstallReferrerClient.InstallReferrerResponse.OK:
                      ReferrerDetails response = null;
                      try {
                          response = referrerClient.getInstallReferrer();
                      } catch (RemoteException e) {
                          e.printStackTrace();
                      }
                      String referrerUrl = response.getInstallReferrer();
                      Log.w("referrer worked", referrerUrl);
                      long referrerClickTime = response.getReferrerClickTimestampSeconds();
                      long appInstallTime = response.getInstallBeginTimestampSeconds();
                      boolean instantExperienceLaunched = response.getGooglePlayInstantParam();
                      break;
                  case InstallReferrerClient.InstallReferrerResponse.FEATURE_NOT_SUPPORTED:
                      // API not available on the current Play Store app.
                      break;
                  case InstallReferrerClient.InstallReferrerResponse.SERVICE_UNAVAILABLE:
                      // Connection couldn't be established.
                      break;
              }
          }
```

**Comment by mikehardy** [comment]
Please propose a PR and we can collaborate on getting it merged

**Comment by heroic** [comment]
I debugged this further. Seems like it works in debug mode, and not in prod, which leads me to believe that the work that was done to make installreferrer optional, caused the need for adding a proguard rule. Trying to find the correct proguard rule.

**Comment by heroic** [comment]
Got it working by adding this to the proguard config. Will add this to the README in a PR

```
-keepclassmembers class com.android.installreferrer.api.** {
  *;
}
```

**Comment by mikehardy** [comment]
Thank you! That sounds about right, if it's reflective now, it may be removed without proguard

**Comment by heroic** [comment]
Created a PR for this
