### ISSUE TITLE
getUserAgent on Galaxy devices / Android 12 causes crash in production

### ISSUE THREAD

**Issue by nluzzato** [react-native-device-info/react-native-device-info#1351]
## Summary
Hi, 
Noticed a lot of weird crashes in our bug monitoring tool, it appears to stem by a ResourceNotFound exception thrown while running the getUserAgent flow, apparently because an error thrown by chromoium which I suppose is used to mount a WebView to extract the user agent from.

| Version     | 8.1.3   |
| Affected OS | Android   |
| OS Version  | 12  |

## Current behavior

I'm fairly certain getUserAgent causes a crash, once I removed it's use the crash went away.

Stack trace:

```
android.content.res.Resources$NotFoundException: Resource ID #0x20c0025        
at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:240)         
at android.content.res.Resources.getInteger(Resources.java:1275)         
at org.chromium.ui.base.DeviceFormFactor.isTablet(Unknown:8)         
at cs.a(Unknown:4)         
at org.chromium.content.browser.BrowserStartupControllerImpl.e(Unknown:25)         
at org.chromium.content.browser.BrowserStartupControllerImpl.g(Unknown:26)         
at E8.run(Unknown:127)         
at org.chromium.base.ThreadUtils.f(Unknown:6)         
at EB0.g(Unknown:209)         
at DB0.run(Unknown:7)         
at android.os.Handler.handleCallback(Handler.java:938)         
at android.os.Handler.dispatchMessage(Handler.java:99)         
at android.os.Looper.loopOnce(Looper.java:226)         
at android.os.Looper.loop(Looper.java:313)         
at android.app.ActivityThread.main(ActivityThread.java:8582)
```

## Expected behavior

Not crash :)

**Comment by mikehardy** [comment]
I fixed the formatting on your issue (triple-backticks are a great markdown trick) so the stack is readable
This is a shame, we're not doing anything non-standard here.

https://github.com/react-native-device-info/react-native-device-info/blob/1a10a875c840bbe1ea0cb00fed592974d32d5f32/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L875

We are even catching RuntimeException which is the base of the android.content.res.Resource.NotFoundException https://developer.android.com/reference/android/content/res/Resources.NotFoundException so we should be catching this

Turns out it's an upstream issue. It's a real issue but there is nothing we can do about it.
Go star the issue here so you may follow along: https://bugs.chromium.org/p/chromium/issues/detail?id=1271617

Closing as not actionable but I do hate crash bugs, sorry this is happening. Disable use of that on samsung android 12 for now I guess, although it appears other versions may be affected as well
