### ISSUE TITLE
RNInstallReferrerClient.java line 90

### ISSUE THREAD

**Issue by pushpender-singh-ap** [react-native-device-info/react-native-device-info#1377]
## Summary

|             |     |
| ----------- | --- |
| Version     | ^8.4.5   |
| Affected OS | Android   |
| OS Version  | 11   |

## Current behavior

<img width="520" alt="Screenshot 2022-02-07 at 12 43 33 AM" src="https://user-images.githubusercontent.com/73298854/152697466-8d92c106-9e07-493a-a83c-39f417d18297.png">
<img width="511" alt="Screenshot 2022-02-07 at 12 45 16 AM" src="https://user-images.githubusercontent.com/73298854/152697517-6d7eae07-95b3-4bc2-80ed-aaa9c9474b99.png">

```
main (native): tid=1 systid=32070
#00 pc 0xc6054 libc.so 
#01 pc 0x82550 libc.so 
#02 pc 0x54cb8 libbinder.so 
#03 pc 0x55d24 libbinder.so 
#04 pc 0x55a8c libbinder.so 
#05 pc 0x4e130 libbinder.so 
#06 pc 0x12880c libandroid_runtime.so 
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:568)
       at com.google.android.a.a.a(BaseProxy.java:5)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.a(IGetInstallReferrerService.java:4)
       at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:9)
       at java.lang.reflect.Method.invoke(Native method)
       at com.learnium.RNDeviceInfo.RNInstallReferrerClient$InstallReferrerStateListenerProxy.onInstallReferrerSetupFinished(RNInstallReferrerClient.java:90)
       at com.learnium.RNDeviceInfo.RNInstallReferrerClient$InstallReferrerStateListenerProxy.invoke(RNInstallReferrerClient.java:71)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at com.android.installreferrer.api.InstallReferrerStateListener.onInstallReferrerSetupFinished(InstallReferrerStateListener.java)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:7)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2165)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2197)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8282)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

## Expected behavior

Crash Free

**Comment by mikehardy** [comment]
I am not aware of how, exactly, *any* line of java code can trigger a native crash that is not a native bug, and outside of the control of the module. It is my understanding that the nature of the java language certainly calls down to truly native (that is: C/C++/Rust/whatever) code but that if there is a crash in a .so file, then the native code is the problem - and we don't control that.

If you are experiencing these crashes, are you calling the install referrer APIs? Stated differently: can you stop calling them, and it's fine? Or is there no workaround at all?

No one else has reported this so I would start - if it was an urgent need - by simply commenting out those lines in the java code inside node_modules and using patch-package to make that work well in your project, while isolating (probably via stackoverflow) what is going on with oppo or vivo install referrer as their implementation appears to be crashing.

You should also triple-check all your dependencies are up to date (all the google play services, react-native etc etc)

**Comment by hukpavlo** [comment]
Same ANR on realme C3, no  install referrer APIs calls, we only use getVersion 

#03 pc 0x55d24 libbinder.so 
#04 pc 0x55a8c libbinder.so 
#05 pc 0x4e130 libbinder.so 
#06 pc 0x12880c libandroid_runtime.so 
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:568)
       at com.google.android.a.a.a(BaseProxy.java:4)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.a(IGetInstallReferrerService.java:4)
       at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:8)
       at java.lang.reflect.Method.invoke(Native method)
       at com.learnium.RNDeviceInfo.RNInstallReferrerClient$InstallReferrerStateListenerProxy.onInstallReferrerSetupFinished(RNInstallReferrerClient.java:90)
       at com.learnium.RNDeviceInfo.RNInstallReferrerClient$InstallReferrerStateListenerProxy.invoke(RNInstallReferrerClient.java:71)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at com.android.installreferrer.api.InstallReferrerStateListener.onInstallReferrerSetupFinished(InstallReferrerStateListener.java)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:5)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2145)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2177)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8192)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by mikehardy** [comment]
@hukpavlo the original author said it was a crash, you are saying it is an ANR - those are quite different things! That would explain things a bit more.

Do you have a Realme C3 device where you reproduce this?
Are you able to see anything during reproduction when you run the app in strict mode to diagnose the ANR?

Regardless, I see two main weaknesses with the current install referrer API, both of which could result in PRs I would happily merge:

1- the documentation clearly indicates the information will be available for 90 days, and will not change unless the app is reinstalled. That indicates to me that we should store information about whether we have already fetched the referrer in the local preferences file, and if we have, then we should not fetch it again. On successful fetch we would then set the new preferences key indicating we've fetched the preference. Note the big "Caution" box on this documentation https://developer.android.com/google/play/installreferrer/library#install-referrer - so right here the preferences could be tested for a new key `installReferrerFetched` and if it was boolean true then quietly return: https://github.com/react-native-device-info/react-native-device-info/blob/d9b8cb5af3c166a914b48fdaa22df0a7dcb8397f/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java#L37

...while right here the key may be set boolean true:
https://github.com/react-native-device-info/react-native-device-info/blob/d9b8cb5af3c166a914b48fdaa22df0a7dcb8397f/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java#L94

I have verified via docs as thoroughly as I can and it appears the SharedPreferences object by default is backed by a file that is removed on uninstall, which means a new install may get a new referrer (correct behavior) but it appears SharedPreferences may be stored in google cloud during account backup to enable easy app backup/restore. That means if the app is restored on a new device or similar the preference keys would still exist - but they would be referring to the same install and thus the old referrer would still be correct, so that's also correct.

This would reduce the number of times the referrer is ever called, meaning that at minimum the incidence of this problem should go way way way down.

2- it appears the install referrer listener is called on the main thread for some reason, **assuming it really is an ANR your app is taking**, so these API calls which may result in network traffic are also on main thread:

https://github.com/react-native-device-info/react-native-device-info/blob/d9b8cb5af3c166a914b48fdaa22df0a7dcb8397f/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java#L86-L98

Those could be refactored to be in a worker Runnable thread. It doesn't appear that there is any communication needed back to the calling thread, the Runnable will either succeed or not and modify preferences or not, but just needs to complete it's work and stop, without getting in the way of the main thread and potentially causing an ANR.

PRs welcome!

**Comment by hukpavlo** [comment]
Thanks for the explanation, unfortunately, I don't have this device and I'm not really familiar with Android development, so I made patch, hope someone with good native experience will help

**Comment by mikehardy** [comment]
Well at least with open source we can patch :-), keeps you moving forward...

**Comment by mikehardy** [comment]
@MartinPavlik check git blame on the relevant stack trace frames, you'll answer your question on updates, it's all open source + info available, no need to ask, just examine

What sort of information do you find on stackoverflow (for example) when you do the relevant research on the stack trace?

**Comment by manuhook** [comment]
Hi,

It's also mentionning ANR on Crashlytics and the problem is quite recurrent.

![Capture d’écran 2023-08-03 à 10 01 18](https://github.com/react-native-device-info/react-native-device-info/assets/531834/132e12d1-deba-4eb0-8948-19d4c3ea8f9f)

```
main (native):tid=1 systid=4582 
#00 pc 0xd6bd4 libc.so (__ioctl + 4) (BuildId: 4cbc2a7636b3e0b018386ca8427ddf9b)
#01 pc 0x928b8 libc.so (ioctl + 156) (BuildId: 4cbc2a7636b3e0b018386ca8427ddf9b)
#02 pc 0x457ac libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 288) (BuildId: 0b78cc6b6a8c79f8b26d96a33500391a)
#03 pc 0x46968 libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*) + 60) (BuildId: 0b78cc6b6a8c79f8b26d96a33500391a)
#04 pc 0x466b8 libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 216) (BuildId: 0b78cc6b6a8c79f8b26d96a33500391a)
#05 pc 0x3e828 libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 212) (BuildId: 0b78cc6b6a8c79f8b26d96a33500391a)
#06 pc 0x3e6a0 libbinder.so (android::BpBinder::getInterfaceDescriptor() const + 292) (BuildId: 0b78cc6b6a8c79f8b26d96a33500391a)
#07 pc 0x3e870 libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 284) (BuildId: 0b78cc6b6a8c79f8b26d96a33500391a)
#08 pc 0x163d9c libandroid_runtime.so (android_os_BinderProxy_transact(_JNIEnv*, _jobject*, int, _jobject*, _jobject*, int) + 152) (BuildId: be6b7249dc547f34e4ce1b4021dbcbfe)
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:629)
       at com.google.android.a.a.a(BaseProxy.java:5)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.a(IGetInstallReferrerService.java:4)
       at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:9)
       at java.lang.reflect.Method.invoke(Native method)
       at com.learnium.RNDeviceInfo.RNInstallReferrerClient$InstallReferrerStateListenerProxy.onInstallReferrerSetupFinished(RNInstallReferrerClient.java:90)
       at com.learnium.RNDeviceInfo.RNInstallReferrerClient$InstallReferrerStateListenerProxy.invoke(RNInstallReferrerClient.java:71)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at com.android.installreferrer.api.InstallReferrerStateListener.onInstallReferrerSetupFinished(InstallReferrerStateListener.java)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:7)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2125)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2158)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8305)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)

```

We are not using [getInstallReferrer()](https://github.com/react-native-device-info/react-native-device-info/issues/1377#getinstallreferrer) in our app.

I've added this proguard rules in our last release has it was missing, will let you know if it's helping. 

```
-keepclassmembers class com.android.installreferrer.api.** {
  *;
}
```

**Comment by manuhook** [comment]
The ANR is still present with the proguard rule.

**Comment by sauravgk** [comment]
Still facing this issue, is this somehow fixed in the newer versions?

**Comment by rahulmmohan** [comment]
<img width="1338" alt="Screenshot 2023-10-18 at 12 06 31 PM" src="https://github.com/react-native-device-info/react-native-device-info/assets/7617176/b043dd1a-9cc7-4e5f-bca4-40e148a41d30">
main (native):tid=1 systid=8016 
#00 pc 0xd7284 libc.so (__ioctl + 4) (BuildId: 351225fa1d718acf9e00214d7dd5d405)
#01 pc 0x92e60 libc.so (ioctl + 152) (BuildId: 351225fa1d718acf9e00214d7dd5d405)
#02 pc 0x45840 libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 288) (BuildId: a874823f4b8316d2b8316797d5c4e32e)
#03 pc 0x469f4 libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*) + 60) (BuildId: a874823f4b8316d2b8316797d5c4e32e)
#04 pc 0x46744 libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 216) (BuildId: a874823f4b8316d2b8316797d5c4e32e)
#05 pc 0x3e8ac libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 192) (BuildId: a874823f4b8316d2b8316797d5c4e32e)
#06 pc 0x166b88 libandroid_runtime.so (android_os_BinderProxy_transact(_JNIEnv*, _jobject*, int, _jobject*, _jobject*, int) + 152) (BuildId: 20f356bdcd6883e755203c4342de5e03)
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:635)
       at com.google.android.a.a.b(BaseProxy.java:2)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.c(IGetInstallReferrerService.java:3)
       at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:5)
       at java.lang.reflect.Method.invoke(Native method)
       at com.learnium.RNDeviceInfo.RNInstallReferrerClient$InstallReferrerStateListenerProxy.onInstallReferrerSetupFinished(RNInstallReferrerClient.java:90)
       at com.learnium.RNDeviceInfo.RNInstallReferrerClient$InstallReferrerStateListenerProxy.invoke(RNInstallReferrerClient.java:71)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at com.android.installreferrer.api.InstallReferrerStateListener.onInstallReferrerSetupFinished(InstallReferrerStateListener.java)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:4)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2240)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2273)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)


Still facing this issue

**Comment by pushpender-singh-ap** [comment]
I am reopening this issue because lot of ppl are facing (I don't have access to the client's project, so I cannot confirm whether this issue is present or not.)

**Comment by sauravgk** [comment]
Still facing this issue

**Comment by unishubh** [comment]
It is still giving ANR on low-end devices like `vivo 2027 (V2029)`.  I am not a native Android Dev, but while digging through the code, I found that `RNInstallReferrerClient` function in Java file `RNInstallReferrerClient` runs on the main thread.

Most of the applications make a lot of API/Memory calls on app start, and also call the getInstallReferrer() method on app start as well,  performing all these on the main thread is the cause of delay, and hence we get the ANR. 

Request the author or any one else well versed in Native Dev to move the `RNInstallReferrerClient` to a background thread. 

Thanks.

**Comment by mikehardy** [comment]
That sounds reasonable @unishubh - I don't have time to do this myself but I would accept a change like that sure

**Comment by Gongreg** [comment]
Given that we were not using referrer information from react-native-device-info, we've created a patch that removes it altogether from the library and released a new version with it: https://github.com/rune/react-native-device-info/pull/1

The ANRs have completely disappeared.

**Comment by Gongreg** [comment]
@ashwanihundwani1986 , no. I don't think it will ever be merged. I assume there are people who use the referrer information as part of this library. So proper fix would be to make sure that the referrer info is accessed without triggering an ANR.

**Comment by ashwanihundwani1986** [comment]
@Gongreg Just a question if you don't mind :) and know you would have tested this. This fix is production ready right?

**Comment by Gongreg** [comment]
Yes, we've been using it since beginning of this year, we didn't experience any other issues related to it and this specific ANR is totally gone.

**Comment by ashwanihundwani1986** [comment]
@Gongreg Thanks a lot for this fix :)
