### ISSUE TITLE
Exception and Execution failed for task ':react-native-device-info:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by iphonic** [react-native-device-info/react-native-device-info#1406]
> System:
>     OS: macOS 11.6.1
>     CPU: (8) x64 Apple M1
>     Memory: 114.99 MB / 16.00 GB
>     Shell: 3.2.57 - /bin/bash
>   Binaries:
>     Node: 14.17.3 - /usr/local/bin/node
>     Yarn: 1.22.15 - /usr/local/bin/yarn
>     npm: 6.14.14 - /usr/local/bin/npm
>     Watchman: Not Found
>   Managers:
>     CocoaPods: 1.10.1 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
>     Android SDK:
>       API Levels: 28, 29, 30, 31
>       Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
>       System Images: android-31 | Google APIs ARM 64 v8a
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: 2021.1 AI-211.7628.21.2111.8309675
>     Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_292 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.2 => 17.0.2 
>     react-native: 0.67.1 => 0.67.1 
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found

## Current behavior

Installed **react-native-device-info 8.7.0**  and compiled, receiving the following error

> java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)
> 	at com.sun.tools.javac.util.Assert.error(Assert.java:133)
> 	at com.sun.tools.javac.code.TypeAnnotations.annotationType(TypeAnnotations.java:231)
> 	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.separateAnnotationsKinds(TypeAnnotations.java:294)
> 	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.visitMethodDef(TypeAnnotations.java:1066)
> 
> ....
> ....

> FAILURE: Build failed with an exception.
> 
> What went wrong:
> Execution failed for task ':react-native-device-info:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.

I am using 

> **Gradle SDK 11.0**, 
> 
> Android Studio Bumblebee | 2021.1.1 Patch 3
> Build #AI-211.7628.21.2111.8309675, built on March 16, 2022
> 
> 
> **build.gradle** looks like this
> 
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     ext {
>         buildToolsVersion = "30.0.2"
>         minSdkVersion = 23
>         compileSdkVersion = 31
>         targetSdkVersion = 31
>         ndkVersion = "21.4.7075529"
>         androidXCore = "1.7.0"
>         googlePlayServicesIidVersion = "17.0.0"
>     }
>     repositories {
>         google()
>         mavenCentral()
> 
>         jcenter()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:4.2.2")
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url("$rootDir/../node_modules/react-native/android")
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
>         mavenCentral {
>             // We don't want to fetch react-native from Maven Central as there are
>             // older versions over there.
>             content {
>                 excludeGroup "com.facebook.react"
>             }
>         }
>         google()
>         jcenter()
>         maven { url 'https://www.jitpack.io' }
>     }
> }

What am I doing wrong?

**Comment by mikehardy** [comment]
You need JDK11 to compile android API 31
The answer to this message comes up on stackoverflow if you search for the error message
