### ISSUE TITLE
NativeEventEmitter require non null argument error when call hasNotch() with Expo

### ISSUE THREAD

**Issue by Julienblc** [react-native-device-info/react-native-device-info#1414]
## Summary

I want to use react-native-device-info with the latest expo version (45). But when I use the `hasNotch()` function, I have these errors : 

on iOS (iPhone se 2nd gen) : 
```
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:6 in guardedLoadModule
at http://192.168.9.29:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:123145:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

on Android (pixel 6) : 
```
Error: react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
  • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
  • Rebuild and re-run the app.
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
  If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-device-info/react-native-device-info
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:6 in guardedLoadModule
at http://192.168.9.29:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:123025:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

|             |     |
| ----------- | --- |
| Version     | 8.7.1  |
| Affected OS | iOS and Android  |
| OS Version  | all I've tested : android 12 or iOS 15.4.1  |

## Current behavior

Here are screenshots from iOS : 
![IMG_0790](https://user-images.githubusercontent.com/7222986/168036616-7925bab2-d121-4724-94ea-6f0eaee651f7.jpg)
![IMG_0789](https://user-images.githubusercontent.com/7222986/168036621-91ee22dd-52fc-4f4d-a906-2b11777ac5d1.jpg)

and screenshots from Android : 
![Screenshot_20220512-111825](https://user-images.githubusercontent.com/7222986/168037226-a847bada-891b-49a1-aa48-7d0907dd3258.png)
![Screenshot_20220512-111841](https://user-images.githubusercontent.com/7222986/168037237-a67476fe-24e5-4d02-8dbb-c44aee64c295.png)

## Expected behavior

Get the boolean depending on the notch

This bug may comes from React Native latest update. I'll investigate in some days if you don't have the time about this bug.

How to reproduce bug : 
- run `expo init test-notch`
- install `yarn add react-native-device-info`
- add `hasNotch()` in any component
- -> BUG

I've created a repo if you want to test it : https://github.com/Julienblc/test-notch

Thank you, and have a nice day !

**Comment by mwmcode** [comment]
Getting the same error when Appium loads iOS bundle on emulator
```
 ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

**Comment by maluramichael** [comment]
I got the same problem. For me its this line here https://github.com/react-native-device-info/react-native-device-info/blob/master/src/internal/asyncHookWrappers.ts#L29 which calls this one https://github.com/facebook/react-native/blob/main/Libraries/EventEmitter/NativeEventEmitter.js#L47

It appears that it is not possible anymore on ios to pass a native module to the event emitter on ios.

**Comment by hoseinfo** [comment]
any update here?
