### ISSUE TITLE
Android crash when install react-native-device-info

### ISSUE THREAD

**Issue by RogerWenXin** [react-native-device-info/react-native-device-info#1417]
## Summary

version: 8.7.1
android sytem: 9

## Android crashed, uninstall this package will recover.

2022-05-18 13:27:20.907 13832-13832/com.appnativechildrenhospital E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.appnativechildrenhospital, PID: 13832
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appnativechildrenhospital/com.appnativechildrenhospital.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2985)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3120)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:687)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:201)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:92)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:86)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46)
        at com.appnativechildrenhospital.MainActivity.onCreate(MainActivity.java:12)
        at android.app.Activity.performCreate(Activity.java:7232)
        at android.app.Activity.performCreate(Activity.java:7221)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965)

**Comment by RogerWenXin** [comment]
I solved by clean project.
