### ISSUE TITLE
Task :react-native-device-info:compileReleaseJavaWithJavac FAILED for Android SDK 31

### ISSUE THREAD

**Issue by sa0sh0iip** [react-native-device-info/react-native-device-info#1457]
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.4.8 or 10.0.2   |
| Affected OS | ANDROID   |
| OS Version  | 31   |
| RN Version  | 65.1   |

## Current behavior

- > Task :react-native-device-info:compileReleaseJavaWithJavac FAILED
An exception has occurred in the compiler (1.8.0_242-release). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)
        at com.sun.tools.javac.util.Assert.error(Assert.java:133)
        at com.sun.tools.javac.code.TypeAnnotations.annotationType(TypeAnnotations.java:231)
        at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.separateAnnotationsKinds(TypeAnnotations.java:294)
        at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.visitMethodDef(TypeAnnotations.java:1066)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
.......
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-device-info:compileReleaseJavaWithJavac'.
Compilation failed; see the compiler error output for details.

## Expected behavior

- `./gradlew assembleRelease` generates a build successfully as it did in following config

|             |     |
| ----------- | --- |
| Version     | 8.4.8 or 10.0.2   |
| Affected OS | ANDROID   |
| OS Version  | 30   |
| RN Version  | 65.1   |

Updating JDK version to 11 will be my last resort for SDK 31. Does anyone have other work-arounds?

**Comment by mikehardy** [comment]
Search https://search.brave.com/search?q=java.lang.AssertionError%3A+annotationType()%3A+unrecognized+Attribute+name+MODULE+(class+com.sun.tools.javac.util.UnsharedNameTable%24NameImpl)&source=desktop

Read https://stackoverflow.com/questions/68344424/unrecognized-attribute-name-module-class-com-sun-tools-javac-util-sharednametab

Use JDK11

Build success!
