### ISSUE TITLE
  Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver com.learnium.RNDeviceInfo.RNDeviceReceiver

### ISSUE THREAD

**Issue by ravi123saxena** [react-native-device-info/react-native-device-info#1643]
Device Details:

Brand:Oppo
Model:A94
Orientation:Portrait

Operating System

Version:Android 13

  Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver com.learnium.RNDeviceInfo.RNDeviceReceiver: java.lang.ClassNotFoundException: Didn't find class "com.learnium.RNDeviceInfo.RNDeviceReceiver" on path: DexPathList[[zip file "/data/app/~~ZUel24e0exMjMeD7uV7i4A==/com.shell.sitibv.shellfleetapp-R6eDIMBf8y0hawCvEln3NA==/base.apk", zip file "/data/app/~~ZUel24e0exMjMeD7uV7i4A==/com.shell.sitibv.shellfleetapp-R6eDIMBf8y0hawCvEln3NA==/split_config.arm64_v8a.apk", zip file "/data/app/~~ZUel24e0exMjMeD7uV7i4A==/com.shell.sitibv.shellfleetapp-R6eDIMBf8y0hawCvEln3NA==/split_config.en.apk", zip file "/data/app/~~ZUel24e0exMjMeD7uV7i4A==/com.shell.sitibv.shellfleetapp-R6eDIMBf8y0hawCvEln3NA==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~ZUel24e0exMjMeD7uV7i4A==/com.shell.sitibv.shellfleetapp-R6eDIMBf8y0hawCvEln3NA==/lib/arm64, /data/app/~~ZUel24e0exMjMeD7uV7i4A==/com.shell.sitibv.shellfleetapp-R6eDIMBf8y0hawCvEln3NA==/base.apk!/lib/arm64-v8a, /data/app/~~ZUel24e0exMjMeD7uV7i4A==/com.shell.sitibv.shellfleetapp-R6eDIMBf8y0hawCvEln3NA==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~ZUel24e0exMjMeD7uV7i4A==/com.shell.sitibv.shellfleetapp-R6eDIMBf8y0hawCvEln3NA==/split_config.en.apk!/lib/arm64-v8a, /data/app/~~ZUel24e0exMjMeD7uV7i4A==/com.shell.sitibv.shellfleetapp-R6eDIMBf8y0hawCvEln3NA==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4515)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8377)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by mav10** [comment]
+1
We got ANR crashes recently from RNDeviceInfo module
phones quite specific like a Oppo, Lenovo etc.

**Comment by edXmO** [comment]
@mav10 If those crashes are from devices running on Android 14 then it might be related to this change [Runtime receiver exported](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported)

Might be related to [App Crashes - On upgrading to Android 14(SDK 34)](https://github.com/facebook/react-native/issues/41288)

**Comment by mikehardy** [comment]
All of our receivers are registered with export behavior specified if the android version level supports / requires it:

https://github.com/react-native-device-info/react-native-device-info/blob/f0aba106ccd73f5165c87e3877f4deb9e6adb50c/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L1067-L1074

If your investigation / code modification tests turns up the reason for the crash, a PR would be welcome
