### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError Failed resolution of: Leeqb;

### ISSUE THREAD

**Issue by amit1ume** [react-native-device-info/react-native-device-info#1683]
## Only a few users are facing this issue
 
 amxj.d (:com.google.android.gms@244631022@24.46.31 (150400-699197446):5)
aiuc.<clinit> (:com.google.android.gms@244631022@24.46.31 (150400-699197446):9)
com.google.android.gms.chimera.container.DynamiteLoaderImpl.<init> (:com.google.android.gms@244631022@24.46.31 (150400-699197446):49)
java.lang.Class.newInstance (Class.java)
com.google.android.gms.dynamite.DynamiteModule.zzg (com.google.android.gms:play-services-basement@@18.3.0:5)
com.google.android.gms.dynamite.DynamiteModule.zza (com.google.android.gms:play-services-basement@@18.3.0:28)
com.google.android.gms.dynamite.zze.zzb (com.google.android.gms:play-services-basement@@18.3.0:1)
com.google.android.gms.dynamite.zzi.selectModule (com.google.android.gms:play-services-basement@@18.3.0:2)
com.google.android.gms.dynamite.DynamiteModule.load (com.google.android.gms:play-services-basement@@18.3.0:7)
com.google.android.gms.internal.measurement.zzdn.zza (zzdn.java:24)
com.google.android.gms.internal.measurement.zzdq.zza (com.google.android.gms:play-services-measurement-sdk-api@@22.0.1:10)
com.google.android.gms.internal.measurement.zzdn$zzb.run (com.google.android.gms:play-services-measurement-sdk-api@@22.0.1:12)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923)

|             |     |
| ----------- | --- |
| Version     | android 11   |
| Affected OS | android 11   |
| OS Version  | android 11   |

## Current behavior

The app is crashing in app start

## Expected behavior

the app should not crash

**Comment by mikehardy** [comment]
I'm not aware of any version released here called "android 11", what version of the plugin are you using?
What code triggers it?
Where in the stack frames do you see any java code from this module, such that the problem will be in this module and we should pay attention here instead of ignoring it since it doesn't appear to be in this module?
How can we reproduce the problem if so?

**Comment by alethanhphonghehe-art** [comment]
ZENNYMOD CRASH REPORT
Time: 2026-09-22 17:38:03
Android: 11 (SDK 30)
Device: Xiaomi M2006C3MG
Thread: main

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/example/shizukupermission/AutoResetReceiver;
	at com.example.shizukupermission.MainActivity$100000035$100000034.run(Unknown Source:35)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7912)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Caused by: java.lang.ClassNotFoundException: com.example.shizukupermission.AutoResetReceiver
	... 8 more

**Comment by alethanhphonghehe-art** [comment]
ZENNYMOD CRASH REPORT
Time: 2026-09-22 17:38:03
Android: 11 (SDK 30)
Device: Xiaomi M2006C3MG
Thread: main

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/example/shizukupermission/AutoResetReceiver;
	at com.example.shizukupermission.MainActivity$100000035$100000034.run(Unknown Source:35)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7912)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Caused by: java.lang.ClassNotFoundException: com.example.shizukupermission.AutoResetReceiver
	... 8 more
